// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuArho0rqQqLCRM2bO7CeEIBJXPEY8_X0',
    appId: '1:79853946102:android:a251659a964e573a43d8d7',
    messagingSenderId: '79853946102',
    projectId: 'finalsoa-fae05',
    storageBucket: 'finalsoa-fae05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjS8f_xJi3D51YJyZTcIY5wGmMkFQ1vgw',
    appId: '1:79853946102:ios:3ff871d7ffefb67443d8d7',
    messagingSenderId: '79853946102',
    projectId: 'finalsoa-fae05',
    storageBucket: 'finalsoa-fae05.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVbWWeKM7gO4Wb3hsHP12RXnsGjNJJq8',
    appId: '1:79853946102:web:f7ce38cd4a766bca43d8d7',
    messagingSenderId: '79853946102',
    projectId: 'finalsoa-fae05',
    authDomain: 'finalsoa-fae05.firebaseapp.com',
    storageBucket: 'finalsoa-fae05.appspot.com',
    measurementId: 'G-5QF5YT3B3R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjS8f_xJi3D51YJyZTcIY5wGmMkFQ1vgw',
    appId: '1:79853946102:ios:3ff871d7ffefb67443d8d7',
    messagingSenderId: '79853946102',
    projectId: 'finalsoa-fae05',
    storageBucket: 'finalsoa-fae05.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVbWWeKM7gO4Wb3hsHP12RXnsGjNJJq8',
    appId: '1:79853946102:web:c0d9875114bd152043d8d7',
    messagingSenderId: '79853946102',
    projectId: 'finalsoa-fae05',
    authDomain: 'finalsoa-fae05.firebaseapp.com',
    storageBucket: 'finalsoa-fae05.appspot.com',
    measurementId: 'G-T8YCSSQF7Y',
  );

}